baseurl = "/"
languageCode = "fr-ca"
title = "Ressources pour les étudiants en actuariat de l'Université laval"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "À propos"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ressources-act"
[[menu.main]]
    name = "Contributeurs"
    url = "/contrib/"
[[menu.main]]
    name = "Projets"
    url = "/projets/"

[params]
    description = "À définir."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "couverture.jpg"
    width = 50
    height = 50
    alt = "Logo"

